# Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.


def fib(max_num):
    prior = 1
    current = 2
    total = 0
    while current <= max_num:
        if current % 2 == 0:
            total += current

        print("Prior: ", prior, " Current: ", current, "Total of even terms: ", total)
        temp = current
        current += prior
        prior = temp

    return total


print("Sum of even terms up to 89: ", fib(89))
print("Sum of even terms up to 4,000,000: ", fib(4000000))
